// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package order

import (
	"github.com/towgo/towgo/appdemos/demo/api/order"
	order2 "github.com/towgo/towgo/appdemos/demo/internal/logic/order"
)

type ControllerV1 struct {
	orderServer *order2.OrderService
}

func NewV1() order.IOrderV1 {
	return &ControllerV1{
		orderServer: order2.New(),
	}
}
