// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"github.com/towgo/towgo/appdemos/demo/api/user"
	user2 "github.com/towgo/towgo/appdemos/demo/internal/logic/user"
)

type ControllerV1 struct {
	userService *user2.UserService
}

func NewV1() user.IUserV1 {
	return &ControllerV1{
		userService: &user2.UserService{},
	}
}
